%YAML 1.2
---
projects:
  - eclipse/microprofile-samples
  - eclipse/microprofile-conference
  - eclipse/microprofile
  - eclipse/microprofile-config
  - eclipse/microprofile-evolution-process
  - jgallimore/microprofile-fault-tolerance
  - eclipse/microprofile-sandbox
  - eclipse/microprofile-health
  - eclipse/microprofile-jwt-auth
  - eclipse/microprofile-bom
  - eclipse/microprofile-metrics
  
